import { Inter } from "next/font/google";
import "../styles/globals.css";
import { Footer, NavBar } from '../components/ComponentIndex';
import { NFTMarketplaceProvider } from "@/Context/NFTMarketplaceContext";
import ClientErrorSuppressor from "../components/ClientErrorSuppressor";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={inter.className}>
        <ClientErrorSuppressor />
        <NFTMarketplaceProvider>
          <NavBar />
          {children}
          <Footer />
        </NFTMarketplaceProvider>
      </body>
    </html>
  );
}
